sudo: false

language: cpp

compiler:
    - gcc
    - clang

env:
    - CONFIG=debug CONFIGPATH=Debug
    - CONFIG=release CONFIGPATH=Release

install:
    - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha6/premake-5.0.0-alpha6-src.zip -O premake.zip
    - unzip premake.zip
    - cd premake-5.0.0-alpha6/build/gmake.unix
    - make config=release
    - cd ../../..
    - mv premake-5.0.0-alpha6/bin/release/premake5 premake5
    - rm -rf premake-5.0.0-alpha6

before_script:
    - ./premake5 gmake

script:
    - make -C proj config=$CONFIG
    - bin/$CONFIGPATH/testrunnre

